### ISSUE TITLE
need source and description when install 

### ISSUE THREAD

**Issue by appop** [ror6ax/kong_injection#1]
you need add source and description,just like 
source = {
  -- these are initially not required to make it work
  url = "git://github.com/Mashape/kong_plugin",
  tag = "0.1.0"
}

description = {
  summary = "Kong is a scalable and customizable API Management Layer built on top of Nginx.",
  homepage = "http://getkong.org",
  license = "MIT"
}

**Comment by ror6ax** [comment]
@appop - thanks for the tip. Any other feedback about the plug-in? I'm looking to extend it's functionality and am interested in use cases.
